givery-bootcamp/dena-2024-team5

- README.md
- backend/internal/controllers/controllers_test_helper.go
- backend/internal/controllers/post_get_detail.go
- backend/internal/controllers/post_get_detail_test.go
- backend/internal/controllers/post_get_list.go
- backend/internal/controllers/post_get_list_test.go
- backend/internal/interfaces/post_get_detail_repository.go
- backend/internal/interfaces/post_get_list_repository.go
- backend/internal/middleware/router.go
- backend/internal/repositories/post_repository.go
- backend/internal/usecases/post_get_detail.go
- backend/internal/usecases/post_get_list_usecase.go
投稿詳細APIを実装しました。
関連して、投稿一覧APIのリファクタリングも行いました。
close #9
> feat: implement post-detail API

- frontend/api/$api.ts
- frontend/api/@types/index.ts
- frontend/api/posts/index.ts
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/app/(user)/page.tsx
- frontend/src/lib/aspidaClient.ts
> APIを利用するコードを、aspidaで自動生成

- Makefile
- README.md
- backend/.env
- backend/docs/docs.go
- backend/docs/swagger.json
- backend/docs/swagger.yaml
- backend/go.mod
- backend/go.sum
- backend/internal/controllers/auth_signin.go
- backend/internal/dependency/container.go
- backend/internal/entities/user.go
- backend/internal/interfaces/user_repository.go
- backend/internal/middleware/router.go
- backend/internal/repositories/model/user.go
- backend/internal/repositories/post_repository.go
- backend/internal/repositories/user_repository.go
- backend/internal/usecases/auth_signin.go
https://github.com/givery-bootcamp/dena-2024-team5/issues/22
- サインインAPIの実装
- サインイン時に、jwtをcookieに設定するようにする
> signin api作成

- .gitignore
- backend/.env
> ignore .env

- backend/docs/docs.go
- backend/docs/swagger.json
- backend/docs/swagger.yaml
- backend/internal/controllers/post_delete.go
- backend/internal/dependency/container.go
- backend/internal/interfaces/post_delete_repository.go
- backend/internal/middleware/router.go
- backend/internal/repositories/post_repository.go
- backend/internal/usecases/post_delete.go
> create post delete API

- mysql/sql/1_create.sql
> add comments table

- frontend/api/$api.ts
- frontend/api/@types/index.ts
- frontend/api/comments/index.ts
- frontend/api/posts/_postID@number/index.ts
- frontend/api/posts/index.ts
- frontend/api/signin/index.ts
- frontend/api/users/index.ts
- frontend/api/users/me/index.ts
openapiの内容をもとにaspidaを更新しました！
CC: @hasegawa282
> update aspida 

- frontend/src/app/(user)/posts/[id]/page.tsx
- frontend/src/components/CommentItem.tsx
- frontend/src/components/CommentPostForm.tsx
> フロントエンド　コメントの閲覧

- mysql/sql/2_insert.sql
> update: mysql/sql/2_insert.sql

- backend/docs/docs.go
- backend/docs/swagger.json
- backend/docs/swagger.yaml
- backend/internal/controller/post_like_add.go
- backend/internal/dependency/container.go
- backend/internal/entity/like.go
- backend/internal/external/mysql.go
- backend/internal/interfaces/like_add_repository.go
- backend/internal/middleware/router.go
- backend/internal/repository/like.go
- backend/internal/repository/model/like.go
- backend/internal/usecase/post_like_add.go
- backend/internal/usecase/usecase_helper.go
- mysql/sql/1_create.sql
- mysql/sql/2_insert.sql
関連: #81 
DBをリセットするため、一度
```
docker compose down -v
```
を実行してください！
> 投稿にいいねをするAPI

- frontend/src/app/(user)/posts/[id]/page.tsx
- frontend/src/components/CommentItem.tsx
- frontend/src/components/deleteCommentDialog.tsx
- frontend/src/utils/deleteComment.ts
> フロント　コメント削除機能

- frontend/src/app/(guest)/signup/page.tsx
- frontend/src/components/SignupForm.tsx
- frontend/src/lib/zod.ts
- frontend/src/utils/signup.ts
> サインアップフォームを実装

- frontend/src/components/Buttons.tsx
> サインアウト後に、明示的に"/"にリダイレクト

- backend/internal/controller/post_like_add.go
- backend/internal/dependency/container.go
- backend/internal/interfaces/user_get_by_name_repository.go
- backend/internal/interfaces/user_get_random_zombie_repository.go
- backend/internal/repository/user.go
- backend/internal/usecase/comment_zombie_new.go
- backend/internal/util/zombie/zombie.go
> update: zombie comment when someone liked

- .github/workflows/deploy.yml
- docker/frontend-cd.Dockerfile
フロントのproductionの環境変数に以下を追加
```
NEXTAUTH_URL=https://team-5.member0005.track-bootcamp.run/
```
> add next auth url

- frontend/src/auth.ts
- frontend/src/utils/encrypt.ts
- mysql/sql/2_insert.sql
> ⚡️ SHA256で暗号化

- mysql/sql/2_insert.sql
> secretの値を指定のものに変更し,passwordを暗号化

- frontend/src/components/SigninDialog.tsx
- frontend/src/components/SigninForm.tsx
- frontend/src/components/dots/organism/top/SiginInSingUpCard.tsx
- frontend/src/lib/zod.ts
> サインインをポップアップで行う

- frontend/src/app/(guest)/page.tsx
- frontend/src/app/(guest)/signup/page.tsx
- frontend/src/components/SignupDialog.tsx
- frontend/src/components/SignupForm.tsx
- frontend/src/components/dots/organism/top/SiginInSingUpCard.tsx
- frontend/src/lib/zod.ts
- frontend/src/utils/signup.ts
> サインアップをポップアップで行う 

- backend/internal/repository/user.go
ユーザー作成時に、user_type=normalを指定するように
> ユーザー作成時にuser_typeをデフォルト指定

- frontend/src/app/(guest)/page.tsx
- frontend/src/components/dots/organism/top/Credits.tsx
> feat creditsとdeveloperをトップページに追加

- backend/internal/config/config.go
- backend/internal/controller/auth_signin.go
cookieのドメインがlocalhost固定になってる
これで通知直る。。。といいなあ
> fix cookie domain

- backend/internal/controller/auth_signin.go
> set same site none
